version: "1.0"

stack:
  name: "locked-in-agent"
  type: "agent-service"
  system: "locked-in"
  ecosystem: "humanitarian-service-marketplace"

# NOTE: This is NOT KERIA. This is a ground-up serverless KERI agent
# implemented in Rust, running on Lambda with DynamoDB persistence.
# KERIA/keripy use LMDB and HIO which require persistent processes.
# This stack scales to zero.

parameters:
  environment: "dev"
  region: "us-west-2"
  tenant_mode: "multi"                # Multi-tenant — each LockedIn user gets an agent
  supported_schemas: []               # TODO: fill with presence_attestation schema SAID from C3
  witness_pool_oobis: []              # TODO: fill from witness-pool stack output
  watcher_oobis: []                   # TODO: fill from watcher-node stack output

# Architecture:
#
#   API Gateway REST (agent API — AID management, credential ops, KERI messages)
#       |
#   Lambda (Rust — stateless agent logic, <50ms cold starts)
#       |
#   +------------------+--------------------+
#   |                  |                    |
#   DynamoDB          Secrets Manager     SQS
#   (agent state,     (key material,      (async processing:
#    KEL,              encrypted via       ACDC issuance,
#    ACDC wallet,      KMS)               delegation,
#    tenant index)                         receipt collection)
#       |
#   EventBridge (agent lifecycle events)

aws_resources:
  - logical_name: AgentAPI
    type: AWS::ApiGateway::RestApi
    purpose: REST API for agent operations — replaces KERIA's 3-port model
    properties:
      endpoints:
        - "POST /boot"                # Agent provisioning (replaces port 3903)
        - "POST /agent/{aid}/events"  # Submit KERI events (replaces port 3901)
        - "GET  /agent/{aid}/kel"     # Query KEL
        - "POST /agent/{aid}/credentials"  # ACDC operations
        - "GET  /agent/{aid}/credentials"  # List credentials
        - "POST /agent/{aid}/oobi"    # OOBI resolution
        - "POST /messages"           # Receive external KERI messages (replaces port 3902)
      authorization: IAM

  - logical_name: AgentFunction
    type: AWS::Lambda::Function
    purpose: Rust Lambda — stateless KERI agent logic
    properties:
      runtime: provided.al2023       # Custom runtime (Rust via cargo-lambda)
      architecture: arm64            # Graviton — cheaper + faster for Rust
      memory: 256                    # Rust is memory-efficient
      timeout: 30
      environment:
        AGENT_TABLE: "{AgentStateTable}"
        KEL_TABLE: "{AgentKELTable}"
        WALLET_TABLE: "{AgentWalletTable}"
        ASYNC_QUEUE: "{AgentAsyncQueue}"
        KEY_SECRET_PREFIX: "locked-in-agent/keys/"
        WITNESS_OOBIS: ""            # TODO: fill from witness-pool output
        WATCHER_OOBIS: ""            # TODO: fill from watcher-node output

  - logical_name: AgentAsyncFunction
    type: AWS::Lambda::Function
    purpose: Rust Lambda — async processing (SQS consumer for delegation, receipts)
    properties:
      runtime: provided.al2023
      architecture: arm64
      memory: 256
      timeout: 300                   # Longer timeout for async ops
      event_source: "{AgentAsyncQueue}"

  - logical_name: AgentStateTable
    type: AWS::DynamoDB::Table
    purpose: Agent state — tenant index, AID metadata, configuration
    properties:
      billing_mode: PAY_PER_REQUEST
      key_schema:
        hash: tenant_id             # Tenant identifier (S)
        range: resource_type        # "agent" | "config" | "oobi" (S)
      gsi:
        - name: AIDIndex
          hash: aid_prefix          # AID prefix for cross-tenant lookups
      point_in_time_recovery: true
      deletion_protection: false    # dev

  - logical_name: AgentKELTable
    type: AWS::DynamoDB::Table
    purpose: KEL storage — per-tenant event logs
    properties:
      billing_mode: PAY_PER_REQUEST
      key_schema:
        hash: prefix                # AID prefix (S)
        range: sn                   # Sequence number (N)
      gsi:
        - name: SAIDIndex
          hash: said                # Event SAID for lookups
      point_in_time_recovery: true
      deletion_protection: false    # dev

  - logical_name: AgentWalletTable
    type: AWS::DynamoDB::Table
    purpose: Credential wallet — ACDC storage per tenant
    properties:
      billing_mode: PAY_PER_REQUEST
      key_schema:
        hash: tenant_id            # Tenant identifier (S)
        range: acdc_said           # ACDC SAID (S)
      gsi:
        - name: SchemaIndex
          hash: schema_said
          range: issued_at
      point_in_time_recovery: true
      deletion_protection: false    # dev

  - logical_name: AgentKeySecret
    type: AWS::SecretsManager::Secret
    purpose: Agent key material template (per-tenant secrets created at provisioning)
    properties:
      kms_key: "{AgentKMSKey.Arn}"

  - logical_name: AgentKMSKey
    type: AWS::KMS::Key
    purpose: Envelope encryption for key material
    properties:
      key_spec: SYMMETRIC_DEFAULT
      enable_rotation: true

  - logical_name: AgentAsyncQueue
    type: AWS::SQS::Queue
    purpose: Async processing for ACDC issuance, delegation, receipts
    properties:
      visibility_timeout: 300
      dead_letter_queue: "{AgentDLQ.Arn}"
      max_receive_count: 3

  - logical_name: AgentDLQ
    type: AWS::SQS::Queue
    purpose: Dead letter queue for failed async operations

  - logical_name: AgentEventBus
    type: AWS::Events::EventBus
    purpose: Agent lifecycle events (provisioning, key rotation, credential ops)
    properties:
      name: "locked-in-agent-events"

networking:
  vpc: default
  subnets: [private]                 # Lambda in private subnets
  security_groups:
    - name: AgentLambdaSG
      purpose: Lambda outbound to DynamoDB + Secrets Manager (via VPC endpoints)
  load_balancer: none                # API Gateway handles routing

monitoring:
  dashboards:
    - "locked-in-agent-operations"
  alarms:
    - name: LambdaErrors
      metric: Errors
      threshold: "> 0 (5min)"
      action: CloudWatch only        # dev
    - name: APILatency
      metric: Latency (API Gateway)
      threshold: "> 500ms (p99)"
      action: CloudWatch only
    - name: DLQMessages
      metric: ApproximateNumberOfMessagesVisible (DLQ)
      threshold: "> 0"
      action: CloudWatch only
    - name: DynamoDBThrottling
      metric: ThrottledRequests
      threshold: "> 0"
      action: CloudWatch only
  log_groups:
    - "/aws/lambda/locked-in-agent"
    - "/aws/lambda/locked-in-agent-async"
    - "/aws/apigateway/locked-in-agent"

outputs:
  - name: AgentApiUrl
    value: "https://{AgentAPI}.execute-api.us-west-2.amazonaws.com/prod"
    description: Agent REST API URL
  - name: BootUrl
    value: "https://{AgentAPI}.execute-api.us-west-2.amazonaws.com/prod/boot"
    description: Agent provisioning URL
  - name: EventBusArn
    value: "{AgentEventBus.Arn}"
    description: EventBridge bus for agent lifecycle events

domain_components: []
