version: "1.0"

stack:
  name: "locked-in-acdc-registry"
  type: "acdc-registry"
  system: "locked-in"
  ecosystem: "humanitarian-service-marketplace"

parameters:
  environment: "dev"
  region: "us-west-2"
  issuer_aid: ""                      # TODO: fill after LockedIn service AID inception
  supported_schemas: []               # TODO: fill with presence_attestation schema SAID from C3
  revocation_policy: "backed"         # Witness-backed revocation for presence attestations
  witness_pool_oobi: ""               # TODO: fill from witness-pool stack output (WitnessOOBIUrl)

# Architecture:
#
#   API Gateway REST (ACDC issuance, revocation, verification)
#       |
#   Lambda (ACDC operations: schema validation, TEL events, sig verification)
#       |
#   +-------------+-----------------+
#   |             |                 |
#   DynamoDB     S3               EventBridge
#   (ACDC +      (immutable       (issuance/revocation
#    TEL,         ACDC docs,       notifications)
#    SAID-        versioned)
#    indexed)

aws_resources:
  - logical_name: RegistryAPI
    type: AWS::ApiGateway::RestApi
    purpose: REST API for ACDC lifecycle operations
    properties:
      endpoints:
        - "POST /credentials"
        - "POST /credentials/{said}/revoke"
        - "GET  /credentials/{said}"
        - "GET  /credentials/{said}/tel"
      authorization: IAM

  - logical_name: RegistryFunction
    type: AWS::Lambda::Function
    purpose: ACDC operations — schema validation, TEL event creation, signature verification
    properties:
      runtime: python3.12
      memory: 512
      timeout: 30
      environment:
        ISSUER_AID: ""                # TODO: fill after AID inception
        REVOCATION_POLICY: "backed"
        WITNESS_OOBI: ""              # TODO: fill from witness-pool output

  - logical_name: ACDCTable
    type: AWS::DynamoDB::Table
    purpose: ACDC storage indexed by SAID — presence attestation credentials
    properties:
      billing_mode: PAY_PER_REQUEST
      key_schema:
        hash: said
      gsi:
        - name: IssuerIndex
          hash: issuer_aid
          range: issued_at
        - name: SchemaIndex
          hash: schema_said
      point_in_time_recovery: true
      deletion_protection: false      # dev

  - logical_name: TELTable
    type: AWS::DynamoDB::Table
    purpose: Transaction Event Log — issuance/revocation state tracking
    properties:
      billing_mode: PAY_PER_REQUEST
      key_schema:
        hash: acdc_said
        range: sn
      point_in_time_recovery: true

  - logical_name: ACDCDocumentBucket
    type: AWS::S3::Bucket
    purpose: Immutable ACDC document storage (presence attestation proofs)
    properties:
      versioning: true
      encryption: AES256
      lifecycle_rules:
        - transition_to_ia: 90
        - transition_to_glacier: 365
      block_public_access: true

  - logical_name: RegistryEventBus
    type: AWS::Events::EventBus
    purpose: ACDC lifecycle event notifications
    properties:
      name: "locked-in-acdc-registry-events"
      rules:
        - name: IssuanceNotification
          pattern: '{"detail-type": ["ACDCIssued"]}'
        - name: RevocationNotification
          pattern: '{"detail-type": ["ACDCRevoked"]}'

networking:
  vpc: default
  subnets: [private]
  security_groups:
    - name: RegistryLambdaSG
      purpose: Lambda outbound to DynamoDB + S3 (via VPC endpoints)
  load_balancer: none

monitoring:
  dashboards:
    - "locked-in-acdc-registry-operations"
  alarms:
    - name: LambdaErrors
      metric: Errors
      threshold: "> 0 (5min)"
      action: CloudWatch only         # dev
    - name: APILatency
      metric: Latency (API Gateway)
      threshold: "> 1s (p99)"
      action: CloudWatch only
    - name: DynamoDBThrottling
      metric: ThrottledRequests
      threshold: "> 0"
      action: CloudWatch only
  log_groups:
    - "/aws/lambda/locked-in-acdc-registry"
    - "/aws/apigateway/locked-in-acdc-registry"

outputs:
  - name: RegistryApiUrl
    value: "https://{RegistryAPI}.execute-api.us-west-2.amazonaws.com/prod"
    description: REST API URL for ACDC operations
  - name: EventBusArn
    value: "{RegistryEventBus.Arn}"
    description: EventBridge bus for issuance/revocation notifications

# C2 UPDATE NEEDED: runtime should be Rust Lambda (provided.al2023), not python3.12.
# keripy LMDB/HIO incompatible with Lambda. See domain/domain.yaml for details.
domain_components:
  - name: registry-event-log-engine
    type: event-log-engine
  - name: registry-acdc-tel-manager
    type: acdc-registry
  - name: registry-oobi-resolver
    type: oobi-resolver
